Draft: Fix for big-endian arch
composewell/unicode-data pull request #98
Opened 2022-12-01 13:48 UTC by wismill

Fix for 32bits words on big-endian arch.

Fixes #97

2022-12-03 09:18 UTC, harendra-kumar requested changes
We need to fix the following files as well for the same issue:

* unicode-data-scripts/test/Unicode/Char/General/ScriptsSpec.hs
* unicode-data-scripts/lib/Unicode/Char/General/Scripts.hs

We may have problems in future if we forget to include MachDeps.h , this is a nasty thing that is not caught by any tool and can be easily missed. We can do two things to mitigate this:

* define a CPP macro for reading Word32 with endianness handling and then use that macro everywhere. That way we need to include MachDeps only in the file defining that macro. Both byteswap and narrowing can be included in that macro so we do not miss it anywhere.
* Add a CI for s390x. We can copy it from unicode-transforms repo.

2022-12-04 14:03 UTC, wismill commented
> We need to fix the following files as well for the same issue:
> 
>     * unicode-data-scripts/test/Unicode/Char/General/ScriptsSpec.hs
> 
>     * unicode-data-scripts/lib/Unicode/Char/General/Scripts.hs
> 

These are already fixed.

> We may have problems in future if we forget to include MachDeps.h , this is a nasty thing that is not caught by any tool and can be easily missed. We can do two things to mitigate this:
> 
>     * define a CPP macro for reading Word32 with endianness handling and then use that macro everywhere. That way we need to include MachDeps only in the file defining that macro. Both byteswap and narrowing can be included in that macro so we do not miss it anywhere.
> 
>     * Add a CI for s390x. We can copy it from unicode-transforms repo.

I think the latter is better. I am giving a try.

2022-12-04 14:11 UTC, wismill commented on unicode-data-names/lib/Unicode/Internal/Char/UnicodeData/DerivedName.hs
> +        word2Int# (narrow32Word# (byteSwap32# (word32ToWord# (indexWord32OffAddr# offsets# k#))))
I did not find much information. I found some hints in `cryptonite` package.

My understanding is that _byte swapping_ adapt the endianness and is not limited to 2 bytes. Here `byteSwap32#` is for 4 bytes, and `byteSwap16#` would be for 2, etc.

2022-12-04 14:12 UTC, wismill commented
@harendra-kumar there is an issue with the CI for GHC 8.0.2 and 8.2.2. It seems they are not supported anymore.

2022-12-04 16:01 UTC, harendra-kumar commented
> > We need to fix the following files as well for the same issue:
> > ```
> > * unicode-data-scripts/test/Unicode/Char/General/ScriptsSpec.hs
> > 
> > * unicode-data-scripts/lib/Unicode/Char/General/Scripts.hs
> > ```
> 
> These are already fixed.

It see this in `unicode-data-scripts/lib/Unicode/Char/General/Scripts.hs`:

```
#ifdef WORDS_BIGENDIAN
#if MIN_VERSION_base(4,16,0)
            byteSwap32# (word32ToWord# (indexWord32OffAddr# addr# k#));
#else
            byteSwap32# (indexWord32OffAddr# addr# k#);
#endif
```

Don't we need a call to narrowWord here?

2022-12-04 16:29 UTC, harendra-kumar commented
> @harendra-kumar there is an issue with the CI for GHC 8.0.2 and 8.2.2. It seems they are not supported anymore.

The installation seems to be failing, not sure what's wrong. We can investigate if someone asks for it, otherwise let's ignore it for now.

2022-12-04 17:16 UTC, wismill commented on .github/workflows/s390x.yml
> +        distro: ubuntu20.04
Yes, that's what I did in #99

2022-12-04 20:00 UTC, wismill commented
After the experiment in #99, I think this is ready to merge if the relevant tests pass (let’s discard GHC ≤ 8.2). Keep in mind that we can fully test only against GHC 9.6. And GHC support for Unicode < 12.1 is not reliable, because there are some discrepancies (I checked manually some errors).

2022-12-05 10:35 UTC, harendra-kumar commented
It seems you missed this https://github.com/composewell/unicode-data/pull/98#issuecomment-1336451077 . Can you please respond to this.

2022-12-05 11:04 UTC, wismill commented
> It seems you missed this [#98 (comment)](https://github.com/composewell/unicode-data/pull/98#issuecomment-1336451077) . Can you please respond to this.

I think I did. Are you using the latest version?

2022-12-16 08:37 UTC, wismill commented
@harendra-kumar kind reminder

2022-12-17 09:25 UTC, harendra-kumar approved these changes

2022-12-17 09:27 UTC, harendra-kumar commented
> I think I did fix it. Are you using the latest version?

Looks like I missed it, maybe I did not pull it again or ignored the pull error.

2022-12-17 12:42 UTC, merged